esphome:
  name: esp8266-scd41
  friendly_name: esp8266-scd41

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "yourkey="

ota:
  password: "yourpw"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp8266-Scd41"
    password: "yourappw"

captive_portal:

i2c:
  sda: D2
  scl: D1
  scan: false
  id: bus_a

    
sensor:
# SCD41
  - platform: scd4x
    co2:
      name: "SCD41 CO2"
    temperature:
      name: "SCD41 Temperatur"
    humidity:
      name: "SCD41 Feuchte"
# Send Update every 60s
    update_interval : 60s
